[versions]
activity = "1.9.3"
agp = "8.7.2"
androidXAnnotation = "1.9.1"
androidXCore = "1.15.0"
appcompat = "1.7.0"
composeBom = "2024.08.00"
composeNavigation = "2.8.4"
composeStableMarker = "1.0.5"
coroutines = "1.9.0"
dokka = "1.9.20"
jupiter = "5.11.3"
kotlin = "2.0.21"
lifecycle = "2.8.7"
material = "1.12.0"
mockK = "1.13.13"
paparazziGradlePlugin = "1.3.5"
testCore = "1.6.1"

[libraries]
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidXAnnotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidXAnnotation" }
androidXCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
buildTools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeFoundation = { group = "androidx.compose.foundation", name = "foundation" }
composeMaterial = { group = "androidx.compose.material", name = "material" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
composeNavigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
composePreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composeStableMarker = { group = "com.github.skydoves", name = "compose-stable-marker", version.ref = "composeStableMarker" }
composeUI = { group = "androidx.compose.ui", name = "ui" }
composeUITooling = { group = "androidx.compose.ui", name = "ui-tooling" }
composeViewBinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
lifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockK = { group = "io.mockk", name = "mockk", version.ref = "mockK" }
paparazziGradlePlugin = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazziGradlePlugin" }
testCore = { group = "androidx.test", name = "core-ktx", version.ref = "testCore" }
viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

[plugins]
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
